# aeziol-language-format: 1
window-title-standard = Aeziol — توجيه الصوت
tagline-standard = يمكن للنشاط الصوتي في Discord توجيه مخرج صوت Windows.
automation-standard = تفعيل توجيه الصوت التلقائي
status-standard = حالة Discord
status-discord-absent-standard = Discord غير قيد التشغيل
status-out-of-voice-standard = Discord يعمل، خارج قناة صوتية
status-connecting-standard = جارٍ الاتصال بالقناة الصوتية…
status-connected-standard = متصل بقناة صوتية
status-disconnected-standard = تم قطع الاتصال الصوتي
status-authorization-required-standard = يلزم تفويض Discord
authorize-discord-standard = تفويض Discord
authorizing-discord-standard = بانتظار Discord…
authorization-failed-standard = تعذر إكمال تفويض Discord.
authorization-cancelled-standard = تم إلغاء تفويض Discord.
authorization-waiting-title-standard = أكّد الطلب في Discord
authorization-waiting-message-standard = يعرض Discord طلبًا منفصلًا. سيبقى Aeziol في الانتظار حتى تختار.
authorization-waiting-hint-standard = أبقِ نافذة Discord مفتوحة
authorization-cancel-standard = إلغاء مقصود
authorization-error-client-id-standard = معرّف تطبيق Discord غير صالح. تحقّق من المعرّف العام المحفوظ في Aeziol.
authorization-error-public-client-standard = رفض Discord تبادل OAuth. تحقّق من تفعيل Public Client ومن مطابقة عنوان إعادة التوجيه تمامًا.
authorization-error-network-standard = تعذر على Aeziol الوصول إلى خدمة OAuth في Discord. تحقّق من الشبكة ثم أعد المحاولة.
authorization-error-rpc-standard = أوقف Discord التفويض المحلي أو رفضه. يوضّح التفصيل التقني أدناه السبب.
technical-detail-standard = التفصيل التقني
status-unavailable-standard = حالة Discord الصوتية غير متاحة
destination-standard = مخرج الصوت أثناء المحادثة
exclusions-standard = مخارج الصوت الحالية المستبعدة
settings-standard = الإعدادات
language-standard = لغة الواجهة
language-name-en-standard = الإنجليزية
language-name-fr-standard = الفرنسية
language-name-ar-standard = العربية
client-id-standard = معرّف تطبيق Discord
client-id-help-standard = معرّف عام فقط — لا تُدخل سر العميل مطلقًا.
autostart-standard = تشغيل Aeziol مع Windows
autostart-open-hidden-standard = فتح Aeziol مخفيًا عند بدء تشغيل Windows
close-behavior-standard = عند الإغلاق
save-standard = حفظ
logs-standard = فتح مجلد السجلات
saved-standard = تم حفظ الإعدادات
recovery-title-standard = تم اكتشاف مسار صوت سابق
recovery-message-standard = أُغلق Aeziol أثناء توجيه الصوت. هل تريد استعادة مخرج Windows السابق الآن؟
close-title-standard = إغلاق Aeziol
close-message-standard = ماذا يجب أن يفعل Aeziol عند إغلاق هذه النافذة؟
close-choice-ask-standard = السؤال دائمًا
close-choice-tray-standard = الاستمرار في منطقة الإعلام
close-choice-quit-standard = إنهاء Aeziol
close-choice-hide-compact-standard = إخفاء
close-choice-quit-compact-standard = إنهاء
close-choice-tray-description-standard = تختفي النافذة، لكن يبقى Aeziol قرب الساعة ويواصل مراقبة Discord.
close-choice-quit-description-standard = تتوقف الأتمتة ويستعيد Aeziol مخرج الصوت عند الحاجة.
close-one-click-hint-standard = نقرة واحدة تطبق الاختيار
recommended-standard = موصى به
close-remember-standard = تذكّر هذا الاختيار
close-remember-settings-note-standard = يمكنك تغييره لاحقًا من الإعدادات > عام > التطبيق.
cancel-standard = إلغاء
confirm-standard = تأكيد
tray-open-standard = فتح Aeziol
tray-quit-standard = خروج
first-run-title-standard = مرحبًا بك في Aeziol
first-run-help-standard = اضبط الخيارات الأساسية. يمكنك تغييرها كلها لاحقًا.
first-run-local-data-standard = تبقى هذه التفضيلات محفوظة محليًا على هذا الكمبيوتر.
first-run-theme-title-standard = اختر لوحة ألوان
first-run-theme-help-standard = تغيّر اللوحة ألوان التمييز فقط، وليس الخلفية الداكنة أو النصوص.
first-run-theme-preview-standard = معاينة الواجهة
first-run-music-title-standard = حضور صوتي، إذا رغبت
first-run-music-help-standard = يتضمن Aeziol موسيقى خلفية اختيارية. تظل معطلة ما لم تختر تشغيلها.
first-run-music-purpose-standard = مرجع صوتي خفيف يجعل تغييرات مخرج الصوت مسموعة فورًا.
first-run-music-enable-standard = تفعيل موسيقى الخلفية
first-run-music-choice-standard = يمكنك تعديل خيارات الموسيقى هذه لاحقًا من الإعدادات.
continue-standard = متابعة
back-standard = رجوع
finish-standard = إنهاء
exclusions-help-standard = يترك Aeziol مخارج الصوت الحالية هذه دون تغيير.
settings-help-standard = اللغة وتفويض Discord وسلوك بدء التشغيل.
routing-applied-standard = تم توجيه مخرج Windows بنجاح.
routing-retargeted-standard = تم تطبيق الوجهة الجديدة مباشرة، مع الاحتفاظ بالمخرج الأصلي للاستعادة.
routing-restored-standard = تمت استعادة مخرج Windows السابق.
routing-excluded-standard = لا تغيير: مخرج الصوت الحالي مستبعد.
routing-target-unavailable-standard = مخرج الصوت المحدد غير متاح حاليًا.
routing-source-unavailable-standard = مخرج الصوت السابق لم يعد متاحًا.
routing-rolled-back-standard = أُلغي التغيير وتمت استعادة مخرج الصوت السابق.
routing-manual-change-standard = تم الاحتفاظ بتغييرك اليدوي لمخرج Windows.
routing-recovery-required-standard = أكّد استعادة مخرج Windows السابق.
routing-failed-standard = تعذر تغيير مخرج Windows بأمان.
nav-passage-standard = الممر
nav-rules-standard = القواعد
nav-settings-standard = الإعدادات
page-passage-title-standard = ممر الصوت
page-passage-subtitle-standard = يفعّل Discord مخرج Windows ثم يعيد Aeziol المخرج السابق.
automation-short-standard = تلقائي
automation-enable-standard = تفعيل
automation-disable-standard = تعطيل
source-standard = المصدر
target-help-standard = تُحفظ التغييرات فورًا.
current-output-standard = مخرج Windows الحالي
restore-output-standard = المخرج الذي سيُستعاد
restore-output-idle-standard = لا استعادة معلّقة
force-restore-standard = فرض الاستعادة
choose-output-standard = اختر مخرجًا
unknown-output-standard = مخرج غير معروف
unavailable-output-standard = المخرج المحفوظ
unavailable-standard = غير متاح
active-standard = نشط
watching-standard = يراقب
paused-standard = متوقف مؤقتًا
page-rules-title-standard = قاعدة Discord
page-rules-subtitle-standard = يبقى المشغّل والوجهة والاستثناءات في مكان واحد.
rule-trigger-standard = المشغّل
rule-name-standard = صوت Discord
rule-when-label-standard = متى
rule-when-standard = عند اكتمال الاتصال بقناة صوتية.
rule-priority-standard = الأولوية
rule-future-standard = ستظهر التطبيقات المستقبلية هنا دون إثقال الممر الرئيسي.
rule-destination-standard = وجهة القاعدة
page-settings-title-standard = الإعدادات
page-settings-subtitle-standard = الاتصال والواجهة وسلوك الخلفية.
settings-section-general-standard = عام
settings-section-discord-standard = Discord
discord-connection-standard = اتصال Discord
discord-route-caption-standard = رابط محلي لمسار الصوت
discord-fallback-title-standard = هل تعذر العثور على Discord؟
discord-fallback-hint-standard = اختر الملف التنفيذي يدويًا فقط إذا فشل الكشف التلقائي.
discord-authorized-standard = التفويض نشط على هذا الكمبيوتر
discord-not-authorized-standard = لم يتم تفويض Discord بعد
revoke-discord-standard = إلغاء التفويض
discord-executable-standard = مسار Discord.exe الاحتياطي
discord-executable-help-standard = يتم الكشف مرة واحدة عند التشغيل الأول. يمكنك تعديل المسار أو إعادة البحث يدويًا.
discord-executable-picker-standard = اختيار Discord.exe
discord-executable-invalid-title-standard = مسار Discord غير صالح
discord-executable-invalid-message-standard = اختر ملف .exe موجودًا أو امسح الحقل.
discord-executable-auto-standard = بحث تلقائي
discord-executable-not-found-title-standard = تعذر العثور على Discord
discord-executable-not-found-message-standard = لم يعثر Aeziol على تثبيت Discord. يمكنك اختيار Discord.exe يدويًا.
browse-standard = استعراض
interface-section-standard = الواجهة
behavior-section-standard = التطبيق
application-section-standard = التطبيق
lifecycle-settings-standard = الإغلاق والاستعادة
maintenance-standard = الأدوات والصيانة
replay-onboarding-standard = إعادة شاشة الترحيب
reduce-animations-standard = تقليل الحركات
ambient-music-standard = موسيقى خلفية
ambient-music-enabled-standard = التشغيل
ambient-music-credit-standard = Suno
ambient-music-volume-standard = مستوى صوت الخلفية
ambient-music-pending-standard = يتم تشغيل «Onde dorée» محليًا بشكل متكرر وتتبع مخرج Windows الحالي.
ambient-music-recommended-standard = 8٪ موصى به
ambient-music-maximum-standard = 100٪
ambient-music-loud-warning-standard = فوق 20٪، قد تحجب الموسيقى تغيّرات مخرج الصوت.
ambient-music-pause-unfocused-standard = إيقاف الموسيقى مؤقتًا عندما لا يكون Aeziol في الواجهة
ambient-music-keep-playing-hidden-standard = إبقاء الموسيقى قيد التشغيل عندما يكون Aeziol مخفيًا
hardware-acceleration-standard = تسريع الأجهزة
hardware-acceleration-restart-standard = يُطبّق عند التشغيل التالي. عطّله عند حدوث تعارضات رسومية.
update-channel-standard = قناة التحديث
update-channel-stable-standard = مستقرة
update-channel-beta-standard = تجريبية
update-channel-help-standard = تستقبل القناة المستقرة الإصدارات النهائية فقط، بينما تستقبل التجريبية إصدارات الاختبار أيضًا.
update-check-standard = البحث عن تحديثات
update-idle-standard = يتحقق Aeziol من هذه القناة تلقائيًا عند بدء التشغيل.
update-checking-standard = جارٍ البحث عن تحديثات…
update-current-standard = Aeziol محدّث.
update-available-standard = يتوفر إصدار جديد:
update-download-standard = تنزيل المثبّت وفتحه
update-downloading-standard = جارٍ التنزيل والتحقق…
update-download-progress-standard = جارٍ التنزيل والتحقق:
update-ready-title-standard = التحديث جاهز
update-ready-message-standard = تم التحقق من الحزمة. سيفتح Windows المثبّت؛ أغلق Aeziol إذا طلب التثبيت ذلك.
update-ready-confirm-standard = فتح المثبّت
update-found-notification-standard = يتوفر تحديث لـ Aeziol في الإعدادات › الأدوات:
update-check-failed-standard = تعذر البحث عن تحديثات الآن.
reset-setting-standard = استعادة القيمة الموصى بها
reset-application-standard = إعادة ضبط إعدادات التطبيق
reset-application-title-standard = إعادة ضبط إعدادات التطبيق؟
reset-application-message-standard = ستعود الواجهة والسلوك والموسيقى وبدء التشغيل إلى القيم الموصى بها. سيبقى اتصال Discord وقواعد الصوت محفوظين.
reset-application-confirm-standard = إعادة ضبط الكل
ambient-music-mute-standard = كتم موسيقى الخلفية
ambient-music-unmute-standard = تشغيل موسيقى الخلفية
grace-period-standard = المهلة قبل الاستعادة
grace-0-standard = فورًا
grace-1-standard = ثانية واحدة — موصى به
grace-2-standard = ثانيتان
grace-period-help-standard = تمنع المهلة القصيرة الاستعادة أثناء انقطاع عابر في اتصال Discord.
close-preview-ask-standard = سيُطلب التأكيد قبل كل إغلاق.
close-preview-tray-standard = تُغلق النافذة ويستمر Aeziol في منطقة الإعلام.
close-preview-quit-standard = يتوقف Aeziol كليًا ويستعيد الصوت عند الحاجة.
revoke-discord-title-standard = إزالة تفويض Discord؟
revoke-discord-message-standard = سيلغي Aeziol الرمز لدى Discord ويمسح نسخته المحلية ويستعيد الصوت عند الحاجة.
revoke-discord-confirm-standard = إلغاء التفويض
revoke-discord-failed-title-standard = لم يؤكد Discord إلغاء التفويض
revoke-discord-failed-message-standard = يمكنك إعادة المحاولة أو نسيان التفويض المحفوظ على هذا الكمبيوتر فقط.
retry-standard = إعادة المحاولة
forget-local-standard = نسيانه على هذا الكمبيوتر
discord-revoked-standard = تم إلغاء تفويض Discord.
discord-forgotten-standard = تم مسح التفويض المحلي.
generic-error-standard = تعذر إكمال العملية. تظهر التفاصيل التقنية أدناه.
current-output-changed-standard = تم تغيير مخرج صوت Windows.
identical-output-warning-standard = مخرج الصوت قبل التغيير وبعده متطابق: لن يُسمع أي تغيير. احتفظ بهذا الاختيار فقط إذا كان مقصودًا.
about-tooltip-standard = حول Aeziol
about-title-standard = حول Aeziol
about-subtitle-standard = أداة محلية خفيفة لتوجيه مسارات الصوت.
about-author-label-standard = أنشأه
about-author-standard = GaetanGrd
about-ai-standard = تم تصميم Aeziol وتطويره بمساعدة الذكاء الاصطناعي. وتبقى القرارات والتوجيه والتحقق النهائي بشرية.
about-music-section-label-standard = موسيقى خلفية مدمجة
about-music-purpose-standard = هي اختيارية، وتعمل أيضًا كمرجع مسموع عندما يغيّر Aeziol مخرج Windows. يمكن ضبط التشغيل ومستوى الصوت من الإعدادات.
about-music-title-standard = Onde dorée
about-music-credit-standard = تم إنشاؤها باستخدام Suno.
about-elgo-standard = مستوحى من عالم Elgo.
about-lore-standard = في شجرة Elgo، كل حكاية ورقة. ويتبع Aeziol عروقها برفق حتى مساراتك الصوتية.
about-github-standard = عرض المشروع على GitHub ↗
about-close-standard = إغلاق
theme-standard = لوحة الألوان
theme-preview-standard = لوحة الألوان النشطة
enhance-contrast-standard = تعزيز التباين
window-minimize-standard = تصغير
window-maximize-standard = تكبير
window-restore-standard = استعادة
window-close-standard = إغلاق
unexpected-error-title-standard = واجه Aeziol خطأً
unexpected-error-message-standard = سيُغلق Aeziol بأمان. تم تسجيل الخطأ في السجلات المحلية، وستظل أي استعادة صوت معلّقة محمية.
