# aeziol-language-format: 1
window-title-standard = Aeziol — audio routing
tagline-standard = Discord voice can guide the Windows output.
automation-standard = Enable automatic audio routing
status-standard = Discord status
status-discord-absent-standard = Discord is not running
status-out-of-voice-standard = Discord is running, outside voice
status-connecting-standard = Connecting to voice…
status-connected-standard = Connected to voice
status-disconnected-standard = Voice disconnected
status-authorization-required-standard = Discord authorization required
authorize-discord-standard = Authorize Discord
authorizing-discord-standard = Waiting for Discord…
authorization-failed-standard = Discord authorization could not be completed.
authorization-cancelled-standard = Discord authorization cancelled.
authorization-waiting-title-standard = Confirm in Discord
authorization-waiting-message-standard = Discord displays a separate request. Aeziol keeps waiting until you make a choice.
authorization-waiting-hint-standard = Keep the Discord window open
authorization-cancel-standard = Cancel intentionally
authorization-error-client-id-standard = The Discord Client ID is invalid. Check the public identifier saved in Aeziol.
authorization-error-public-client-standard = Discord rejected the OAuth exchange. Check that Public Client is enabled and that the redirect URI matches exactly.
authorization-error-network-standard = Aeziol could not reach Discord’s OAuth service. Check the network connection, then try again.
authorization-error-rpc-standard = Discord interrupted or rejected local authorization. The technical detail below identifies the cause.
technical-detail-standard = Technical detail
status-unavailable-standard = Discord voice status unavailable
destination-standard = Voice audio output
exclusions-standard = Excluded current outputs
settings-standard = Preferences
language-standard = Interface language
language-name-en-standard = English
language-name-fr-standard = French
language-name-ar-standard = Arabic
client-id-standard = Discord application Client ID
client-id-help-standard = Public identifier only — never enter a client secret.
autostart-standard = Start Aeziol with Windows
close-behavior-standard = On close
save-standard = Save
logs-standard = Open logs folder
saved-standard = Preferences saved
recovery-title-standard = Previous audio route detected
recovery-message-standard = Aeziol closed while audio was redirected. Restore the previous Windows output now?
close-title-standard = Close Aeziol
close-message-standard = What should Aeziol do when this window closes?
close-choice-ask-standard = Always ask
close-choice-tray-standard = Keep running in the notification area
close-choice-quit-standard = Quit Aeziol
close-choice-hide-compact-standard = Hide
close-choice-quit-compact-standard = Quit
close-choice-tray-description-standard = The window disappears, but Aeziol keeps watch near the clock and continues monitoring Discord.
close-choice-quit-description-standard = Automation stops and Aeziol restores the audio output when needed.
close-one-click-hint-standard = One click applies the choice
recommended-standard = Recommended
close-remember-standard = Remember this choice
cancel-standard = Cancel
confirm-standard = Confirm
tray-open-standard = Open Aeziol
tray-quit-standard = Quit
first-run-title-standard = Welcome to Aeziol
first-run-help-standard = Set the essentials. You can change every option later.
first-run-local-data-standard = These preferences stay stored locally on this PC.
first-run-theme-title-standard = Choose a color palette
first-run-theme-help-standard = This changes the accents, not the dark background or text.
first-run-theme-preview-standard = Interface preview
first-run-music-title-standard = A sound presence, if you want it
first-run-music-help-standard = Aeziol includes optional ambient music. It stays disabled unless you choose it.
first-run-music-purpose-standard = A subtle reference that makes audio-output changes immediately audible.
first-run-music-enable-standard = Enable ambient music
first-run-music-choice-standard = You can mute it instantly from the title bar or adjust its volume in Settings.
continue-standard = Continue
back-standard = Back
finish-standard = Finish
exclusions-help-standard = Aeziol leaves these current outputs unchanged.
settings-help-standard = Language, Discord authorization, and startup behavior.
routing-applied-standard = Windows output redirected successfully.
routing-retargeted-standard = New destination applied directly. The original output is still saved for restoration.
routing-restored-standard = Previous Windows output restored.
routing-excluded-standard = No change: the current output is excluded.
routing-target-unavailable-standard = The selected output is currently unavailable.
routing-source-unavailable-standard = The previous output is no longer available.
routing-rolled-back-standard = The change was canceled and the previous output was restored.
routing-manual-change-standard = Your manual Windows output change was kept.
routing-recovery-required-standard = Confirm restoration of the previous Windows output.
routing-failed-standard = The Windows output could not be changed safely.
nav-discord-standard = Discord
nav-passage-standard = Passage
nav-coming-soon-standard = Coming soon
nav-settings-standard = Settings
page-discord-title-standard = Discord
page-discord-subtitle-standard = Route Discord voice sessions and configure their automation rule.
discord-section-overview-standard = Audio routing
discord-section-rule-standard = Discord rule
automation-short-standard = Automatic
automation-enable-standard = Enable
automation-disable-standard = Disable
source-standard = Source
target-help-standard = Changes are saved immediately.
current-output-standard = Current Windows output
restore-output-standard = Output to restore
restore-output-idle-standard = No restoration pending
force-restore-standard = Force restoration
choose-output-standard = Choose an output
unknown-output-standard = Unknown output
unavailable-output-standard = Configured output
unavailable-standard = Unavailable
active-standard = Active
watching-standard = Watching
paused-standard = Paused
page-rules-title-standard = Discord rule
page-rules-subtitle-standard = Trigger, destination, and exceptions stay together.
rule-trigger-standard = Trigger
rule-name-standard = Discord voice
rule-when-label-standard = When
rule-when-standard = A voice channel connection is fully established.
rule-priority-standard = Priority
rule-future-standard = Future applications will appear here without cluttering the main passage.
rule-destination-standard = Rule destination
page-settings-title-standard = Settings
page-settings-subtitle-standard = Connection, interface, and background behavior.
settings-section-general-standard = General
settings-section-discord-standard = Discord
discord-connection-standard = Discord connection
discord-route-caption-standard = Local link for the audio passage
discord-fallback-title-standard = Discord not found?
discord-fallback-hint-standard = Select the executable only if automatic detection fails.
discord-authorized-standard = Authorization active on this PC
discord-not-authorized-standard = Discord is not authorized yet
revoke-discord-standard = Revoke
discord-executable-standard = Discord.exe path (fallback)
discord-executable-help-standard = Detected only on first launch. You can edit the path directly or run the search again.
discord-executable-picker-standard = Select Discord.exe
discord-executable-invalid-title-standard = Invalid Discord path
discord-executable-invalid-message-standard = Select an existing .exe file or clear the field.
discord-executable-auto-standard = Find automatically
discord-executable-not-found-title-standard = Discord was not found
discord-executable-not-found-message-standard = Aeziol could not find a Discord installation. You can select Discord.exe manually.
browse-standard = Browse
interface-section-standard = Interface
behavior-section-standard = Application
application-section-standard = Application
lifecycle-settings-standard = Close and restoration
maintenance-standard = Tools and maintenance
replay-onboarding-standard = Replay the welcome screen
reduce-animations-standard = Reduce animations
ambient-music-standard = Ambient music
ambient-music-enabled-standard = Playback
ambient-music-credit-standard = Suno
ambient-music-volume-standard = Background volume
ambient-music-pending-standard = “Onde dorée” plays locally in a loop and follows the current Windows output.
ambient-music-recommended-standard = 8% recommended
ambient-music-maximum-standard = 100%
ambient-music-loud-warning-standard = Above 20%, the music may mask audio output changes.
ambient-music-pause-unfocused-standard = Pause when Aeziol is no longer in the foreground
hardware-acceleration-standard = Hardware acceleration
hardware-acceleration-restart-standard = Applied on next start. Disable it if graphical conflicts occur.
update-channel-standard = Update channel
update-channel-stable-standard = Stable
update-channel-beta-standard = Beta
update-channel-help-standard = Stable receives finalized versions only. Beta also receives test versions.
update-check-standard = Check for updates
update-idle-standard = Aeziol checks this channel automatically at startup.
update-checking-standard = Checking for updates…
update-current-standard = Aeziol is up to date.
update-available-standard = A new version is available:
update-download-standard = Download and open installer
update-downloading-standard = Downloading and verifying…
update-download-progress-standard = Downloading and verifying:
update-ready-title-standard = Update ready
update-ready-message-standard = The package was verified. Windows will open the installer; close Aeziol if installation asks you to.
update-ready-confirm-standard = Open installer
update-found-notification-standard = An Aeziol update is available in Settings › Tools:
update-check-failed-standard = Aeziol could not check for updates right now.
reset-setting-standard = Restore the recommended value
reset-application-standard = Reset application settings
reset-application-title-standard = Reset application settings?
reset-application-message-standard = Interface, behavior, music, and startup will return to recommended values. Discord connection and audio rules will be kept.
reset-application-confirm-standard = Reset everything
ambient-music-mute-standard = Mute ambient music
ambient-music-unmute-standard = Unmute ambient music
grace-period-standard = Delay before restoration
grace-0-standard = Immediate
grace-1-standard = 1 second — recommended
grace-2-standard = 2 seconds
grace-period-help-standard = A short margin prevents restoration during a brief Discord connection drop.
close-preview-ask-standard = A confirmation will be requested before every close.
close-preview-tray-standard = The window closes, but Aeziol keeps running in the notification area.
close-preview-quit-standard = Aeziol stops completely and restores sound when needed.
revoke-discord-title-standard = Remove Discord authorization?
revoke-discord-message-standard = Aeziol will revoke the token with Discord, clear its local copy, and restore sound if needed.
revoke-discord-confirm-standard = Revoke authorization
revoke-discord-failed-title-standard = Discord did not confirm revocation
revoke-discord-failed-message-standard = You can retry or forget only the authorization stored on this PC.
retry-standard = Retry
forget-local-standard = Forget on this PC
discord-revoked-standard = Discord authorization was revoked.
discord-forgotten-standard = Local authorization was cleared.
generic-error-standard = An operation could not be completed. Technical details are shown below.
current-output-changed-standard = The Windows output was changed.
identical-output-warning-standard = The before and after outputs are identical: no audio change will be heard. Keep this choice only if intentional.
about-tooltip-standard = About Aeziol
about-title-standard = About Aeziol
about-subtitle-standard = A lightweight local tool for guiding your sound paths.
about-author-label-standard = Created by
about-author-standard = GaetanGrd
about-ai-standard = Aeziol was designed and developed with the assistance of artificial intelligence. Its choices, direction, and final validation remain human.
about-music-section-label-standard = Built-in ambient music
about-music-purpose-standard = Optional, it also provides an audible reference when Aeziol changes the Windows output. Playback and volume are available in Settings.
about-music-title-standard = Onde dorée
about-music-credit-standard = Generated with Suno.
about-elgo-standard = Inspired by the world of Elgo.
about-lore-standard = In Elgo’s Tree, every story is a leaf. Aeziol gently follows its veins into your sound paths.
about-github-standard = View the project on GitHub ↗
about-close-standard = Close
theme-standard = Color palette
theme-preview-standard = Active palette
enhance-contrast-standard = Enhance contrast
window-minimize-standard = Minimize
window-maximize-standard = Maximize
window-restore-standard = Restore
window-close-standard = Close
unexpected-error-title-standard = Aeziol encountered an error
unexpected-error-message-standard = Aeziol will close safely. The error was recorded in the local logs, and any pending audio restoration remains protected.
