# aeziol-language-format: 1
window-title-standard = Aeziol — routage audio
tagline-standard = L’activité vocale de Discord peut guider la sortie audio Windows.
automation-standard = Activer le routage audio automatique
status-standard = État de Discord
status-discord-absent-standard = Discord n’est pas lancé
status-out-of-voice-standard = Discord est lancé, hors salon vocal
status-connecting-standard = Connexion au salon vocal…
status-connected-standard = Connecté à un salon vocal
status-disconnected-standard = Déconnecté du salon vocal
status-authorization-required-standard = Autorisation Discord requise
authorize-discord-standard = Autoriser Discord
authorizing-discord-standard = En attente de Discord…
authorization-failed-standard = L’autorisation Discord n’a pas pu être terminée.
authorization-cancelled-standard = Autorisation Discord annulée.
authorization-waiting-title-standard = Confirmez dans Discord
authorization-waiting-message-standard = Discord affiche une demande séparée. Aeziol reste en attente tant que vous n’avez pas choisi.
authorization-waiting-hint-standard = Gardez la fenêtre Discord ouverte
authorization-cancel-standard = Annuler volontairement
authorization-error-client-id-standard = Le Client ID Discord est invalide. Vérifiez l’identifiant public enregistré dans Aeziol.
authorization-error-public-client-standard = Discord a refusé l’échange OAuth. Vérifiez que « Public Client » est activé et que l’URI de redirection correspond exactement.
authorization-error-network-standard = Aeziol n’a pas pu joindre le service OAuth de Discord. Vérifiez la connexion réseau, puis réessayez.
authorization-error-rpc-standard = Discord a interrompu ou refusé l’autorisation locale. Le détail technique ci-dessous permet d’en identifier la cause.
technical-detail-standard = Détail technique
status-unavailable-standard = État vocal Discord indisponible
destination-standard = Sortie audio pendant un vocal
exclusions-standard = Sorties actuelles exclues
settings-standard = Paramètres
language-standard = Langue de l’interface
language-name-en-standard = Anglais
language-name-fr-standard = Français
language-name-ar-standard = Arabe
client-id-standard = Client ID de l’application Discord
client-id-help-standard = Identifiant public uniquement — ne saisissez jamais de client secret.
autostart-standard = Lancer Aeziol avec Windows
autostart-open-hidden-standard = Ouvrir Aeziol masqué au démarrage de Windows
close-behavior-standard = À la fermeture
save-standard = Enregistrer
logs-standard = Ouvrir le dossier des journaux
saved-standard = Paramètres enregistrés
recovery-title-standard = Routage audio précédent détecté
recovery-message-standard = Aeziol s’est fermé pendant un routage. Restaurer maintenant l’ancienne sortie Windows ?
close-title-standard = Fermer Aeziol
close-message-standard = Que doit faire Aeziol à la fermeture de cette fenêtre ?
close-choice-ask-standard = Toujours demander
close-choice-tray-standard = Continuer dans la zone de notification
close-choice-quit-standard = Quitter Aeziol
close-choice-hide-compact-standard = Cacher
close-choice-quit-compact-standard = Quitter
close-choice-tray-description-standard = La fenêtre disparaît, mais Aeziol veille près de l’horloge et continue de surveiller Discord.
close-choice-quit-description-standard = L’automatisation s’arrête et Aeziol restaure la sortie audio si nécessaire.
close-one-click-hint-standard = Un clic applique le choix
recommended-standard = Recommandé
close-remember-standard = Mémoriser ce choix
close-remember-settings-note-standard = Vous pourrez le modifier dans Paramètres > Général > Application.
cancel-standard = Annuler
confirm-standard = Confirmer
tray-open-standard = Ouvrir Aeziol
tray-quit-standard = Quitter
first-run-title-standard = Bienvenue dans Aeziol
first-run-help-standard = Réglez l’essentiel. Vous pourrez tout modifier plus tard.
first-run-local-data-standard = Ces préférences restent enregistrées localement sur ce PC.
first-run-theme-title-standard = Choisissez une palette de couleurs
first-run-theme-help-standard = Elle modifie les accents, pas le fond sombre ni les textes.
first-run-theme-preview-standard = Aperçu de l’interface
first-run-music-title-standard = Une présence sonore, si vous la souhaitez
first-run-music-help-standard = Aeziol contient une musique d’ambiance facultative. Elle reste désactivée tant que vous ne la choisissez pas.
first-run-music-purpose-standard = Un repère discret pour entendre immédiatement les changements de sortie audio.
first-run-music-enable-standard = Activer la musique d’ambiance
first-run-music-choice-standard = Vous pourrez modifier ces options musicales plus tard dans les paramètres.
continue-standard = Continuer
back-standard = Retour
finish-standard = Terminer
exclusions-help-standard = Aeziol laisse ces sorties actuelles inchangées.
settings-help-standard = Langue, autorisation Discord et comportement au démarrage.
routing-applied-standard = La sortie Windows a été redirigée.
routing-retargeted-standard = Nouvelle destination appliquée directement. La sortie d’origine reste mémorisée pour la restauration.
routing-restored-standard = La sortie Windows précédente a été restaurée.
routing-excluded-standard = Aucun changement : la sortie actuelle est exclue.
routing-target-unavailable-standard = La sortie sélectionnée est actuellement indisponible.
routing-source-unavailable-standard = La sortie précédente n’est plus disponible.
routing-rolled-back-standard = Le changement a été annulé et l’ancienne sortie restaurée.
routing-manual-change-standard = Votre changement manuel de sortie Windows est conservé.
routing-recovery-required-standard = Confirmez la restauration de l’ancienne sortie Windows.
routing-failed-standard = La sortie Windows n’a pas pu être modifiée en sécurité.
nav-discord-standard = Discord
nav-passage-standard = Passage
nav-coming-soon-standard = À venir
nav-settings-standard = Réglages
page-discord-title-standard = Discord
page-discord-subtitle-standard = Gérez le routage des sessions vocales Discord et leur règle d’automatisation.
discord-section-overview-standard = Routage audio
discord-section-rule-standard = Règle Discord
automation-short-standard = Automatique
automation-enable-standard = Activer
automation-disable-standard = Désactiver
source-standard = Source
target-help-standard = Le changement est enregistré immédiatement.
current-output-standard = Sortie Windows actuelle
restore-output-standard = Sortie à restaurer
restore-output-idle-standard = Aucune restauration en attente
force-restore-standard = Forcer la restauration
choose-output-standard = Choisissez une sortie
unknown-output-standard = Sortie inconnue
unavailable-output-standard = Sortie configurée
unavailable-standard = Indisponible
active-standard = Actif
watching-standard = En veille
paused-standard = En pause
page-rules-title-standard = Règle Discord
page-rules-subtitle-standard = Le déclencheur, la destination et les exceptions restent réunis au même endroit.
rule-trigger-standard = Déclencheur
rule-name-standard = Vocal Discord
rule-when-label-standard = Quand
rule-when-standard = La connexion à un salon vocal est complètement établie.
rule-priority-standard = Priorité
rule-future-standard = Les futures applications apparaîtront ici sans alourdir le passage principal.
rule-destination-standard = Destination de cette règle
page-settings-title-standard = Réglages
page-settings-subtitle-standard = Connexion, interface et comportement de fond.
settings-section-general-standard = Général
settings-section-discord-standard = Discord
discord-connection-standard = Connexion Discord
discord-route-caption-standard = Liaison locale du passage audio
discord-fallback-title-standard = Discord introuvable ?
discord-fallback-hint-standard = Choisissez l’exécutable uniquement si la détection automatique échoue.
discord-authorized-standard = Autorisation active sur ce PC
discord-not-authorized-standard = Discord n’est pas encore autorisé
revoke-discord-standard = Révoquer
discord-executable-standard = Chemin de Discord.exe (secours)
discord-executable-help-standard = Détecté uniquement au premier lancement. Vous pouvez modifier le chemin ou relancer la recherche.
discord-executable-picker-standard = Sélectionner Discord.exe
discord-executable-invalid-title-standard = Chemin Discord invalide
discord-executable-invalid-message-standard = Sélectionnez un fichier .exe existant ou videz le champ.
discord-executable-auto-standard = Chercher automatiquement
discord-executable-not-found-title-standard = Discord est introuvable
discord-executable-not-found-message-standard = Aeziol n’a trouvé aucune installation de Discord. Vous pouvez sélectionner Discord.exe manuellement.
browse-standard = Parcourir
interface-section-standard = Interface
behavior-section-standard = Application
application-section-standard = Application
lifecycle-settings-standard = Fermeture et restauration
maintenance-standard = Outils et maintenance
replay-onboarding-standard = Relancer l’écran de bienvenue
reduce-animations-standard = Réduire les animations
ambient-music-standard = Musique d’ambiance
ambient-music-enabled-standard = Lecture
ambient-music-credit-standard = Suno
ambient-music-volume-standard = Volume en arrière-plan
ambient-music-pending-standard = « Onde dorée » est lue localement en boucle et suit la sortie Windows actuelle.
ambient-music-recommended-standard = 8 % recommandé
ambient-music-maximum-standard = 100 %
ambient-music-loud-warning-standard = Au-delà de 20 %, la musique peut masquer les changements de sortie audio.
ambient-music-pause-unfocused-standard = Mettre en pause quand Aeziol n’est plus au premier plan
ambient-music-keep-playing-hidden-standard = Laisser la musique active quand Aeziol est masqué
ambient-music-focus-precedence-standard = La pause à la perte du premier plan est prioritaire sur la lecture en mode masqué.
hardware-acceleration-standard = Accélération matérielle
hardware-acceleration-restart-standard = Appliqué au prochain démarrage. À désactiver en cas de conflit graphique.
update-channel-standard = Canal de mise à jour
update-channel-stable-standard = Stable
update-channel-beta-standard = Bêta
update-channel-help-standard = Stable reçoit uniquement les versions finalisées. Bêta reçoit aussi les versions de test.
update-check-standard = Rechercher une mise à jour
update-idle-standard = Aeziol vérifie automatiquement ce canal au démarrage.
update-checking-standard = Recherche en cours…
update-current-standard = Aeziol est à jour.
update-available-standard = Une nouvelle version est disponible :
update-download-standard = Télécharger et ouvrir l’installation
update-downloading-standard = Téléchargement et vérification…
update-download-progress-standard = Téléchargement et vérification :
update-ready-title-standard = Mise à jour prête
update-ready-message-standard = Le paquet a été vérifié. Windows va ouvrir l’installateur ; fermez Aeziol si l’installation le demande.
update-ready-confirm-standard = Ouvrir l’installateur
update-found-notification-standard = Une mise à jour Aeziol est disponible dans Réglages › Outils :
update-check-failed-standard = Impossible de vérifier les mises à jour pour le moment.
reset-setting-standard = Rétablir la valeur recommandée
reset-application-standard = Réinitialiser les réglages de l’application
reset-application-title-standard = Réinitialiser les réglages de l’application ?
reset-application-message-standard = Interface, comportement, musique et démarrage reviendront aux valeurs recommandées. La connexion Discord et les règles audio seront conservées.
reset-application-confirm-standard = Tout réinitialiser
ambient-music-mute-standard = Couper la musique d’ambiance
ambient-music-unmute-standard = Rétablir la musique d’ambiance
grace-period-standard = Délai avant restauration
grace-0-standard = Immédiat
grace-1-standard = 1 seconde — recommandé
grace-2-standard = 2 secondes
grace-period-help-standard = Une courte marge évite une restauration lors d’un bref décrochage de Discord.
close-preview-ask-standard = Une confirmation sera demandée avant chaque fermeture.
close-preview-tray-standard = La fenêtre se ferme, mais Aeziol continue dans la zone de notification.
close-preview-quit-standard = Aeziol s’arrête complètement et restaure le son si nécessaire.
revoke-discord-title-standard = Retirer l’autorisation Discord ?
revoke-discord-message-standard = Aeziol révoquera le jeton auprès de Discord, effacera sa copie locale et restaurera le son si nécessaire.
revoke-discord-confirm-standard = Révoquer l’autorisation
revoke-discord-failed-title-standard = Discord n’a pas confirmé la révocation
revoke-discord-failed-message-standard = Vous pouvez réessayer ou oublier uniquement l’autorisation enregistrée sur ce PC.
retry-standard = Réessayer
forget-local-standard = Oublier sur ce PC
discord-revoked-standard = L’autorisation Discord a été révoquée.
discord-forgotten-standard = L’autorisation locale a été effacée.
generic-error-standard = Une opération n’a pas pu être terminée. Le détail technique est indiqué ci-dessous.
current-output-changed-standard = La sortie Windows a été modifiée.
identical-output-warning-standard = Même sortie avant et après : aucun changement audio ne sera audible. Gardez ce choix seulement si c’est volontaire.
about-tooltip-standard = À propos d’Aeziol
about-title-standard = À propos d’Aeziol
about-subtitle-standard = Un outil local et léger pour guider vos chemins sonores.
about-author-label-standard = Créé par
about-author-standard = GaetanGrd
about-ai-standard = Aeziol a été conçu et développé avec l’aide de l’intelligence artificielle. Les choix, la direction et la validation finale restent humains.
about-music-section-label-standard = Musique d’ambiance intégrée
about-music-purpose-standard = Facultative, elle sert aussi de repère audible lorsque Aeziol change la sortie Windows. Lecture et volume se règlent dans Paramètres.
about-music-title-standard = Onde dorée
about-music-credit-standard = Générée avec Suno.
about-elgo-standard = Inspiré de l’univers d’Elgo.
about-lore-standard = Dans l’Arbre d’Elgo, chaque histoire est une feuille. Aeziol en suit doucement les nervures jusque dans vos passages sonores.
about-github-standard = Voir le projet sur GitHub ↗
about-close-standard = Fermer
theme-standard = Palette de couleurs
theme-preview-standard = Palette active
enhance-contrast-standard = Accentuer le contraste
window-minimize-standard = Réduire
window-maximize-standard = Agrandir
window-restore-standard = Restaurer
window-close-standard = Fermer
unexpected-error-title-standard = Aeziol a rencontré une erreur
unexpected-error-message-standard = Aeziol va se fermer proprement. L’erreur a été enregistrée dans les journaux locaux et toute restauration audio en attente reste protégée.
